CADENZA-37830 CADENZA-37929 feat: Document support to show, fetch and download reports generated from report template embedding targets as PDF
DisyInformationssysteme/cadenza.js pull request #63
Opened 2024-11-06 08:31 UTC by sebastianbarth-disy

UI Change reviewed by Jürgen Wäldele

2024-11-06 09:13 UTC, jkissel requested changes

2024-11-06 16:36 UTC, sebastianbarth-disy commented on sandbox.html
> +      PDF (Jasper Report, Report Template)
Report Templates / Berichtsvorlagen is a defined term. But I see your point: In traditional Cadenza speak we would "Generate and export Reports from Report Templates". 

Report Templates can be "Exported" via Manage Workbook dialog, which will open the "Exporting Report" dialog. In the Embeddable Content dialog they are referenced as "Report".

I'll pass this to PO/TR/UX for discussion.

2024-11-06 16:37 UTC, sebastianbarth-disy commented on src/cadenza.js
> +   *     to show the report PDF directly, without any Cadenza headers or footers and embedding targets for report templates.
Will improve...

2024-11-06 16:38 UTC, sebastianbarth-disy commented on src/cadenza.js
> +   *   and `"pdf"` for views of type "JasperReports report" and embedding targets for report templates.
Adhoc Reports are not part of this. Curious, what Workbook Reports are compared to Reports generated from Report Templates. PO/UX/TR will sort out...

2024-11-06 16:40 UTC, sebastianbarth-disy commented on CHANGELOG.md
> +- Support to show, fetch and download reports generated from report template embedding targets as PDF
I thought I group this change together with the corresponding change of Cadenza to support it. But ok, I will limit it to Cadenza JS.

2024-11-07 09:40 UTC, jkissel commented on sandbox.html
> +      PDF (Jasper Report, Report Template)
:+1:

2024-11-07 16:06 UTC, jkissel approved these changes

2024-11-07 19:48 UTC, merged